Update automate.md
replicatedhq/help-center pull request #1074
Opened 2021-09-14 19:44 UTC by JustinN-Replicated

Changing to remove team tokens and replace with service accounts
@jeffreygolden I'm not too sure how to update the images - sorry for this. Could you help or could you walk me through so I can fish? :)

2021-09-14 19:55 UTC, JustinN-Replicated commented
IMO we should likely ferry towards Service Account and not User tokens. WDYAT?

2022-06-08 20:29 UTC, erquhart requested changes

2022-06-08 20:29 UTC, erquhart commented on content/guides/ship-with-docker-swarm/automate.md
> +Ensure the token has the appropriate "Write" access in the selected [RBAC policy](https://vendor.replicated.com/team/policies) selected for the token or you'll be unable create new releases. Once you
"selected" used twice
```suggestion
Ensure the token has the appropriate "Write" access in the [RBAC policy](https://vendor.replicated.com/team/policies) selected for the token or you'll be unable create new releases. Once you have the values,
```

2022-06-08 21:58 UTC, erquhart approved these changes

2022-06-13 16:16 UTC, JustinN-Replicated commented
closing as this file no longer exists in main

2022-06-13 16:16 UTC, closed without merging